/**
 * Seed the first SEO content cluster.
 *
 * Usage (local D1): npm run seed:seo -- --local
 * Usage (remote D1): npm run seed:seo
 * Requires CLOUDFLARE_ACCOUNT_ID for remote Wrangler commands.
 */
import { execFileSync } from 'node:child_process'

const local = process.argv.includes('--local')
const wranglerArgs = ['d1', 'execute', 'DB', ...(local ? ['--local'] : ['--remote']), '--command']

const esc = (value: string) => value.replaceAll("'", "''")
const json = (value: unknown) => esc(JSON.stringify(value))
const now = Math.floor(Date.now() / 1000)

const ids = {
  categories: 'col-categories-d8563a2b',
  products: 'col-products-ce613aa5',
  articles: 'col-articles-f7a0326f',
  authors: 'col-authors-5dc12aff',
  user: 'usr-admin-001'
}

type RecordItem = { id: string; collection: string; slug: string; title: string; data: Record<string, unknown> }

const categories: RecordItem[] = [
  { id: 'cat-mice', collection: ids.categories, slug: 'mice', title: 'Gaming Mice', data: { name: 'Gaming Mice', slug: 'mice', description: 'Gaming mouse reviews for FPS, MOBA, and everyday play.', icon: '🖱️', order: 1, isActive: true } },
  { id: 'cat-keyboards', collection: ids.categories, slug: 'keyboards', title: 'Gaming Keyboards', data: { name: 'Gaming Keyboards', slug: 'keyboards', description: 'Mechanical and magnetic gaming keyboard reviews.', icon: '⌨️', order: 2, isActive: true } },
  { id: 'cat-headsets', collection: ids.categories, slug: 'headsets', title: 'Gaming Headsets', data: { name: 'Gaming Headsets', slug: 'headsets', description: 'Gaming headset reviews for competitive audio and chat.', icon: '🎧', order: 3, isActive: true } },
  { id: 'cat-monitors', collection: ids.categories, slug: 'monitors', title: 'Gaming Monitors', data: { name: 'Gaming Monitors', slug: 'monitors', description: 'Gaming monitor reviews, refresh rates, and panel comparisons.', icon: '🖥️', order: 4, isActive: true } }
]

const products: RecordItem[] = [
  { id: 'prod-logitech-g305', collection: ids.products, slug: 'logitech-g305-lightspeed-review', title: 'Logitech G305 LIGHTSPEED', data: { name: 'Logitech G305 LIGHTSPEED', brand: 'Logitech', slug: 'logitech-g305-lightspeed-review', category: 'cat-mice', price: 39.99, priceRange: 'budget', specs: { weight: '99 g', connectivity: 'wireless' }, rating: { overall: 8.6, buildQuality: 8.5, performance: 9, value: 9.2 }, pros: ['Excellent sensor performance', 'Reliable wireless connection', 'Long battery life'], cons: ['Heavy compared with modern ultralight mice', 'Basic stock feet'], verdict: 'The Logitech G305 remains one of the best budget wireless gaming mice for FPS players and small-to-medium hands.', bestFor: ['fps-games', 'budget', 'wireless'], seo: { title: 'Logitech G305 LIGHTSPEED Review: Best Budget Mouse?', description: 'Our Logitech G305 LIGHTSPEED review covers performance, weight, battery life, comfort, and whether it is still the best budget gaming mouse.', focusKeyword: 'logitech g305 lightspeed' }, status: 'published', publishedAt: now, updatedAt: now, featured: true } },
  { id: 'prod-arctis-nova-pro', collection: ids.products, slug: 'steelseries-arctis-nova-pro-wireless-review', title: 'SteelSeries Arctis Nova Pro Wireless', data: { name: 'SteelSeries Arctis Nova Pro Wireless', brand: 'SteelSeries', slug: 'steelseries-arctis-nova-pro-wireless-review', category: 'cat-headsets', price: 349.99, priceRange: 'ultra-premium', specs: { connectivity: 'wireless' }, rating: { overall: 9, buildQuality: 9, performance: 9.3, value: 8.2 }, pros: ['Excellent multi-platform wireless audio', 'Hot-swappable batteries', 'Strong microphone and ANC'], cons: ['Expensive', 'Tight fit for some users'], verdict: 'A premium wireless headset with exceptional flexibility, but its price makes the value case highly personal.', bestFor: ['premium', 'wireless'], seo: { title: 'SteelSeries Arctis Nova Pro Wireless Review', description: 'SteelSeries Arctis Nova Pro Wireless review: sound, microphone, ANC, battery life, comfort, and value for PC and console gamers.', focusKeyword: 'steelseries arctis nova pro' }, status: 'published', publishedAt: now, updatedAt: now, featured: true } },
  { id: 'prod-rk61', collection: ids.products, slug: 'royal-kludge-rk61-review', title: 'Royal Kludge RK61', data: { name: 'Royal Kludge RK61', brand: 'Royal Kludge', slug: 'royal-kludge-rk61-review', category: 'cat-keyboards', price: 59.99, priceRange: 'mid-range', specs: { connectivity: 'both' }, rating: { overall: 8.1, buildQuality: 7.8, performance: 8.2, value: 8.7 }, pros: ['Compact 60% layout', 'Good wireless value', 'Hot-swappable variants available'], cons: ['Limited dedicated keys', 'Software is basic'], verdict: 'The RK61 is an affordable entry point into compact mechanical keyboards and wireless gaming setups.', bestFor: ['budget', 'wireless'], seo: { title: 'Royal Kludge RK61 Review: Compact Wireless Value', description: 'Royal Kludge RK61 review covering switches, wireless modes, typing feel, gaming performance, and the best alternatives.', focusKeyword: 'royal kludge rk61' }, status: 'published', publishedAt: now, updatedAt: now } },
  { id: 'prod-keychron-q1-pro', collection: ids.products, slug: 'keychron-q1-pro-review', title: 'Keychron Q1 Pro', data: { name: 'Keychron Q1 Pro', brand: 'Keychron', slug: 'keychron-q1-pro-review', category: 'cat-keyboards', price: 199.99, priceRange: 'premium', specs: { connectivity: 'both' }, rating: { overall: 8.8, buildQuality: 9.4, performance: 8.5, value: 8.2 }, pros: ['Excellent aluminum build', 'Wireless QMK/VIA support', 'Deep, customizable sound'], cons: ['Heavy', 'Not the fastest gaming-focused board'], verdict: 'The Keychron Q1 Pro is a premium enthusiast keyboard that also works well for gaming and productivity.', bestFor: ['premium', 'wireless'], seo: { title: 'Keychron Q1 Pro Review: Premium Wireless Mechanical Keyboard', description: 'Keychron Q1 Pro review covering build quality, QMK/VIA, wireless performance, sound, and gaming suitability.', focusKeyword: 'keychron q1 pro' }, status: 'published', publishedAt: now, updatedAt: now } },
  { id: 'prod-lg-27gp850', collection: ids.products, slug: 'lg-27gp850-b-review', title: 'LG 27GP850-B', data: { name: 'LG 27GP850-B', brand: 'LG', slug: 'lg-27gp850-b-review', category: 'cat-monitors', price: 299.99, priceRange: 'premium', specs: { dimensions: '27-inch', connectivity: 'wired', additionalSpecs: '2560x1440, 165Hz, Nano IPS' }, rating: { overall: 8.7, buildQuality: 8.5, performance: 9.1, value: 8.5 }, pros: ['Fast 1440p IPS performance', 'Excellent motion clarity', 'Wide color gamut'], cons: ['IPS contrast is average', 'HDR is limited'], verdict: 'The LG 27GP850-B is a dependable 1440p high-refresh monitor for competitive and single-player gaming.', bestFor: ['fps-games', 'premium'], seo: { title: 'LG 27GP850-B Review: Still a Great 1440p 165Hz Monitor?', description: 'LG 27GP850-B review covering 1440p image quality, 165Hz motion, response times, HDR, and alternatives.', focusKeyword: 'lg 27gp850-b' }, status: 'published', publishedAt: now, updatedAt: now, featured: true } },
  { id: 'prod-asus-pg27aqdm', collection: ids.products, slug: 'asus-rog-swift-oled-pg27aqdm-review', title: 'ASUS ROG Swift OLED PG27AQDM', data: { name: 'ASUS ROG Swift OLED PG27AQDM', brand: 'ASUS', slug: 'asus-rog-swift-oled-pg27aqdm-review', category: 'cat-monitors', price: 699.99, priceRange: 'ultra-premium', specs: { dimensions: '27-inch', connectivity: 'wired', additionalSpecs: '2560x1440, 240Hz, OLED' }, rating: { overall: 9.1, buildQuality: 8.8, performance: 9.7, value: 8.1 }, pros: ['Outstanding OLED contrast', '240Hz motion clarity', 'Very fast response time'], cons: ['Burn-in considerations', 'Premium price'], verdict: 'The PG27AQDM delivers a spectacular 1440p OLED gaming experience for buyers who prioritize motion and contrast.', bestFor: ['fps-games', 'premium'], seo: { title: 'ASUS ROG Swift OLED PG27AQDM Review', description: 'ASUS PG27AQDM review: 1440p 240Hz OLED performance, response times, HDR, burn-in considerations, and value.', focusKeyword: 'asus rog swift oled pg27aqdm' }, status: 'published', publishedAt: now, updatedAt: now, featured: true } }
]

const articles: RecordItem[] = [
  { id: 'art-g305-vs-budget', collection: ids.articles, slug: 'best-budget-gaming-mouse-logitech-g305', title: 'Best Budget Gaming Mouse: Is the Logitech G305 Still Worth It?', data: { title: 'Best Budget Gaming Mouse: Is the Logitech G305 Still Worth It?', slug: 'best-budget-gaming-mouse-logitech-g305', type: 'list', category: 'cat-mice', excerpt: 'A practical guide to choosing a budget gaming mouse, with the Logitech G305 LIGHTSPEED as the benchmark.', content: '<h2>Why the G305 remains the benchmark</h2><p>The Logitech G305 combines a proven sensor, dependable wireless performance, and excellent battery life at a low price. It is still a strong choice for FPS players who want wireless without a premium price.</p><h2>What to check before buying</h2><p>Compare shape, weight, grip style, click feel, and feet. Small-hand users should pay particular attention to the shell dimensions and hump position.</p><h2>Alternatives</h2><p>Consider newer ultralight wireless mice when weight matters more than battery life. The G305 remains the value pick when reliability and price are the priority.</p>', featuredProducts: ['prod-logitech-g305'], seo: { title: 'Best Budget Gaming Mouse: Logitech G305 Review', description: 'Is the Logitech G305 still the best budget gaming mouse? We compare wireless performance, shape, weight, battery life, and alternatives.', focusKeyword: 'budget gaming mouse' }, author: 'author-editor', status: 'published', publishedAt: now, updatedAt: now, readingTime: 6, featured: true } },
  { id: 'art-wooting-vs-razer', collection: ids.articles, slug: 'wooting-80he-vs-razer-huntsman-v3-pro', title: 'Wooting 80HE vs Razer Huntsman V3 Pro: Which Magnetic Keyboard Wins?', data: { title: 'Wooting 80HE vs Razer Huntsman V3 Pro: Which Magnetic Keyboard Wins?', slug: 'wooting-80he-vs-razer-huntsman-v3-pro', type: 'comparison', category: 'cat-keyboards', excerpt: 'A focused comparison of actuation, rapid trigger, software, typing feel, and value for competitive gaming.', content: '<h2>At a glance</h2><p>Both keyboards use magnetic switches and adjustable actuation. The Wooting 80HE leads on software flexibility, while the Huntsman V3 Pro offers a familiar Razer ecosystem and a strong competitive feature set.</p><h2>Performance</h2><p>Rapid trigger and per-key actuation are useful for fast FPS movement, but consistency and comfortable tuning matter more than headline specifications.</p><h2>Verdict</h2><p>Choose Wooting for the deepest customization. Choose Razer when you prefer its layout, support, and ecosystem.</p>', seo: { title: 'Wooting 80HE vs Razer Huntsman V3 Pro', description: 'Wooting 80HE vs Razer Huntsman V3 Pro comparison: rapid trigger, actuation, software, sound, and value.', focusKeyword: 'wooting 80he vs razer huntsman' }, author: 'author-editor', status: 'published', publishedAt: now, updatedAt: now, readingTime: 8, featured: true } },
  { id: 'art-budget-setup', collection: ids.articles, slug: 'best-gaming-setup-under-200', title: 'Best Gaming Setup Under $200', data: { title: 'Best Gaming Setup Under $200', slug: 'best-gaming-setup-under-200', type: 'guide', category: 'cat-mice', excerpt: 'A realistic $200 gaming gear plan covering mouse, keyboard, headset, and upgrade priorities.', content: '<h2>Start with the controls</h2><p>Put the largest share of the budget into a reliable mouse and keyboard. The G305 and RK61 form a practical wireless-friendly foundation.</p><h2>Where to save</h2><p>Use an existing headset or monitor first. Audio and display upgrades are easier to evaluate once the control devices fit your play style.</p><h2>Upgrade order</h2><p>Upgrade the component that limits your sessions most: shape and comfort first, then latency and display performance.</p>', featuredProducts: ['prod-logitech-g305', 'prod-rk61'], seo: { title: 'Best Gaming Setup Under $200: Budget Gear Guide', description: 'Build a capable gaming setup under $200 with practical recommendations for mouse, keyboard, headset, and upgrade priorities.', focusKeyword: 'gaming setup budget 200' }, author: 'author-editor', status: 'published', publishedAt: now, updatedAt: now, readingTime: 7 } },
  { id: 'art-small-mouse', collection: ids.articles, slug: 'best-small-gaming-mouse', title: 'Best Small Gaming Mouse for Small Hands', data: { title: 'Best Small Gaming Mouse for Small Hands', slug: 'best-small-gaming-mouse', type: 'list', category: 'cat-mice', excerpt: 'How to choose a small gaming mouse by hand size, grip, weight, and sensor performance.', content: '<h2>Measure before you buy</h2><p>Hand length and grip style matter more than marketing labels. Compare shell length, width, and hump position to your natural grip.</p><h2>What makes a mouse feel small</h2><p>A narrow front, shorter shell, and lower overall height usually help fingertip and claw users. Weight should remain balanced rather than simply minimized.</p><h2>Our buying checklist</h2><p>Check return policies, wireless latency, click durability, and whether replacement feet are available.</p>', featuredProducts: ['prod-logitech-g305'], seo: { title: 'Best Small Gaming Mouse for Small Hands', description: 'Find the best small gaming mouse by comparing shape, grip, weight, sensor performance, and wireless reliability.', focusKeyword: 'small gaming mouse' }, author: 'author-editor', status: 'published', publishedAt: now, updatedAt: now, readingTime: 6 } }
]

const author: RecordItem = { id: 'author-editor', collection: ids.authors, slug: 'gearlab-editorial-team', title: 'GearLab Editorial Team', data: { name: 'GearLab Editorial Team', slug: 'gearlab-editorial-team', title: 'Gaming Gear Editors', bio: 'Independent gaming gear reviews focused on measurable performance, comfort, and long-term value.', expertise: ['mice', 'keyboards', 'headsets', 'monitors'], yearsExperience: 10, isActive: true } }

const sql = [...categories, author, ...products, ...articles].map((item) =>
  `DELETE FROM content WHERE slug='${esc(item.slug)}'; INSERT INTO content (id, collection_id, slug, title, data, status, published_at, author_id, created_at, updated_at) VALUES ('${esc(item.id)}','${esc(item.collection)}','${esc(item.slug)}','${esc(item.title)}','${json(item.data)}','published',${now},'${ids.user}',${now},${now});`
).join('\n')

const systemSql = `SELECT 1;
${sql}`

execFileSync('npx', ['wrangler', ...wranglerArgs, systemSql], { stdio: 'inherit' })
console.log(`Seeded ${categories.length} categories, ${products.length} products, and ${articles.length} articles (${local ? 'local' : 'remote'} D1).`)
